# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='biography',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost', verbose_name='\u0411\u0438\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
            preserve_default=False,
        ),
    ]
