# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 19:54
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, upload_to='static/image')),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
