# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 13:39
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160207_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='\u0412\u0438\u0434\u0435\u043e'),
        ),
    ]
